name: TikTok Live Check

on:
  schedule:
    # تشغيل آلي كل 5 دقائق
    - cron: '*/5 * * * *'
  workflow_dispatch: # يتيح لك التشغيل اليدوي من المتصفح

jobs:
  check-live:
    runs-on: ubuntu-latest
    # منع العملية من الاستمرار للأبد
    timeout-minutes: 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run TikTok Check
        env:
          # تأكد من تطابق هذه الأسماء مع ما وضعته في إعدادات GitHub Secrets
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node index.js
